// src/components/title.tsx
import { index as $currentTrack, playlist as $playlist } from "@/lib/stores";
import { useStore } from "@nanostores/react";
import { Music2 } from "lucide-react";
import { useEffect, useState, type JSX } from "react";

export default function Title({
	artist,
	id,
	indicatePlaying,
	title,
}: {
	artist: string;
	id: string;
	indicatePlaying?: boolean;
	title: string;
}): JSX.Element {
	const [ok, setOk] = useState(true);
	const [playing, setPlaying] = useState(false);
	const currentTrack = useStore($currentTrack);
	const playlist = useStore($playlist);
	useEffect(() => {
		if (!playlist[currentTrack] || !indicatePlaying) return;
		if (playlist[currentTrack].id === id) setPlaying(true);
		else setPlaying(false);
	}, [playlist[currentTrack]]);
	return (
		<div className="flex items-center gap-2">
			{!ok && (
				<span className="bg-muted flex items-center justify-center rounded-sm p-2">
					<Music2 className="text-muted-foreground" />
				</span>
			)}
			<img
				src={`/api/cover?id=${id}`}
				className={`size-10 rounded-sm ${ok ? "block" : "hidden"}`}
				alt=""
				loading="lazy"
				onLoad={() => setOk(true)}
				onError={() => setOk(false)}
			/>
			<div className="flex flex-col">
				<span
					className={`truncate ${indicatePlaying && playing && "font-semibold"}`}
				>
					{title}
				</span>
				<span className="text-muted-foreground text-sm">{artist}</span>
			</div>
		</div>
	);
}

// src/components/tracks/title.svelte
<script lang="ts">
	import type { track as trackTable } from "@/lib/schema";
	import { index, queue } from "@/lib/stores";
	import { cn } from "@/lib/utils";
	import { Avatar } from "bits-ui";
	import { Icon, MusicalNote } from "svelte-hero-icons";

	interface Props {
		track: typeof trackTable.$inferSelect;
	}
	const { track }: Props = $props();

	const current = $derived($queue.at($index));
</script>

<div class="flex items-center gap-1">
	<Avatar.Root>
		<Avatar.Image
			alt="{track.album || track.title} {track.album && 'album'} cover"
			class="size-10 rounded-sm"
			draggable={false}
			src="/api/track/cover/{track.id}"
		/>
		<Avatar.Fallback
			class="bg-bg1 flex size-10 items-center justify-center rounded-sm"
		>
			<Icon class="text-bg5 size-8" src={MusicalNote} />
		</Avatar.Fallback>
	</Avatar.Root>
	<div class="flex min-w-0 flex-col">
		<span
			class={cn(
				"truncate",
				current === track ? "font-semibold" : "font-normal"
			)}>{track.title}</span
		>
		<span class="text-fg2 truncate text-sm">{track.artist}</span>
	</div>
</div>
