// src/components/ui/button.tsx
import { cn } from "@/lib/utils";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import * as React from "react";

const buttonVariants = cva(
	"focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive inline-flex shrink-0 items-center justify-center gap-2 rounded-md text-sm font-medium whitespace-nowrap transition-all outline-none focus-visible:ring-[3px] disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
	{
		variants: {
			variant: {
				default:
					"bg-primary text-primary-foreground hover:bg-primary/90 shadow-xs",
				destructive:
					"bg-destructive hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60 text-white shadow-xs",
				outline:
					"bg-background hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50 border shadow-xs",
				secondary:
					"bg-secondary text-secondary-foreground hover:bg-secondary/80 shadow-xs",
				ghost:
					"hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
				link: "text-primary underline-offset-4 hover:underline",
			},
			size: {
				default: "h-9 px-4 py-2 has-[>svg]:px-3",
				sm: "h-8 gap-1.5 rounded-md px-3 has-[>svg]:px-2.5",
				lg: "h-10 rounded-md px-6 has-[>svg]:px-4",
				icon: "size-9",
			},
		},
		defaultVariants: {
			variant: "default",
			size: "default",
		},
	}
);

function Button({
	className,
	variant,
	size,
	asChild = false,
	...props
}: React.ComponentProps<"button"> &
	VariantProps<typeof buttonVariants> & {
		asChild?: boolean;
	}) {
	const Comp = asChild ? Slot : "button";

	return (
		<Comp
			data-slot="button"
			className={cn(buttonVariants({ variant, size, className }))}
			{...props}
		/>
	);
}

export { Button, buttonVariants };

// src/components/button.svelte
<script lang="ts">
	import { cn } from "../lib/utils";
	import Loader from "./loader.svelte";
	import { Button } from "bits-ui";
	import { cva, type VariantProps } from "class-variance-authority";
	import type { Snippet } from "svelte";

	const buttonVariants = cva(
		"focus-visible:ring-bg4/50 inline-flex shrink-0 cursor-pointer items-center justify-center rounded-sm text-sm font-medium text-nowrap transition-colors duration-150 focus-visible:ring-[2.5px] focus-visible:outline-none disabled:cursor-default disabled:cursor-not-allowed [&_svg]:size-4",
		{
			variants: {
				size: {
					sm: "h-8 gap-1.5 px-3 has-[>svg]:px-2.5 [&_svg]:size-4",
					lg: "h-10 gap-2 px-6 has-[div[class*='i-']]:px-4 [&_div[class*='i-']]:text-lg",
					icon: "size-8",
				},
				variant: {
					default:
						"bg-primary text-bg hover:bg-primary/95 disabled:hover:bg-primary disabled:opacity-75",
					secondary:
						"bg-bg1 text-fg hover:bg-bg2 hover:text-fg0 disabled:hover:text-fg disabled:hover:bg-bg1 disabled:opacity-75",
					outline:
						"border-bg3 disabled:border-bg3/75 disabled:text-fg/75 disabled:bg-bg1/25 text-fg hover:bg-bg border bg-transparent disabled:hover:bg-transparent",
					ghost:
						"text-fg hover:bg-bg1/50 disabled:opacity-75 disabled:hover:bg-transparent",
					destructive:
						"bg-destructive text-bg hover:bg-destructive/80 disabled:hover:bg-destructive disabled:opacity-75",
				},
			},
			defaultVariants: {
				size: "sm",
				variant: "default",
			},
		}
	);

	type Props = {
		children: Snippet;
		loading?: boolean;
	} & Button.RootProps &
		VariantProps<typeof buttonVariants>;
	const {
		children,
		class: className,
		loading = false,
		size,
		variant,
		...props
	}: Props = $props();
</script>

<Button.Root
	class={cn(buttonVariants({ className, size, variant }))}
	draggable={false}
	disabled={loading}
	{...props}
	>{#if loading}<Loader />
	{:else}{@render children()}{/if}</Button.Root
>
