// src/components/ui/checkbox.tsx
import { cn } from "@/lib/utils";
import * as CheckboxPrimitive from "@radix-ui/react-checkbox";
import { CheckIcon } from "lucide-react";
import * as React from "react";

function Checkbox({
	className,
	...props
}: React.ComponentProps<typeof CheckboxPrimitive.Root>) {
	return (
		<CheckboxPrimitive.Root
			data-slot="checkbox"
			className={cn(
				"peer border-input dark:bg-input/30 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground dark:data-[state=checked]:bg-primary data-[state=checked]:border-primary focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive size-4 shrink-0 rounded-[4px] border shadow-xs transition-shadow outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50",
				className
			)}
			{...props}
		>
			<CheckboxPrimitive.Indicator
				data-slot="checkbox-indicator"
				className="flex items-center justify-center text-current transition-none"
			>
				<CheckIcon className="size-3.5" />
			</CheckboxPrimitive.Indicator>
		</CheckboxPrimitive.Root>
	);
}

export { Checkbox };

// src/components/checkbox.svelte
<script lang="ts">
	import { cn } from "@/lib/utils";
	import { Checkbox } from "bits-ui";
	import { Icon, Check } from "svelte-hero-icons";

	interface Props extends Checkbox.RootProps {
		checked: boolean;
		class?: string;
	}
	let { checked = $bindable(), class: className, ...props }: Props = $props();
</script>

<Checkbox.Root
	bind:checked
	class={cn(
		"bg-bg1 data-[state=checked]:bg-fg data-[state=checked]:border-fg2 border-bg3 group flex size-4 items-center justify-center rounded-sm border disabled:opacity-50",
		className
	)}
	{...props}
>
	{#if checked}
		<Icon class="text-bg size-3" src={Check} micro />
	{/if}
</Checkbox.Root>
