// src/components/forms/signup.svelte
<script lang="ts">
	import Formfield from "./formfield.svelte";
	import Button from "@/components/button.svelte";
	import { newAuthClient as authClient } from "@/lib/auth/client";
	import { reporter } from "@felte/reporter-svelte";
	import { validator } from "@felte/validator-zod";
	import { navigate } from "astro:transitions/client";
	import { createForm } from "felte";
	import { toast } from "sonner";
	import { object, string, type infer as zInfer } from "zod";

	const schema = object({
		name: string().nonempty("required"),
		email: string().nonempty("required").email("invalid email"),
		password: string()
			.nonempty("required")
			.min(8, "must be at least 8 characters long")
			.regex(/\d/, "must have a digit")
			.regex(/[^a-zA-Z0-9]/, "must have a special character"),
	});
	type Schema = zInfer<typeof schema>;

	const { form, isSubmitting } = createForm<Schema>({
		extend: [reporter(), validator({ schema })],
		onSubmit: async (values) => {
			await authClient.signUp.email(
				{
					name: values.name,
					email: values.email,
					password: values.password,
				},
				{
					onSuccess: () => {
						toast.success(
							"Your account has been registered. Verify your email before signing in."
						);
						navigate("/auth/signin");
					},
					onError: ({ error }) => {
						toast.error(`Failed to sign up: ${error.message}`);
					},
				}
			);
		},
	});
</script>

<form class="flex flex-col gap-2" use:form>
	<Formfield name="Name" />
	<Formfield name="Email" />
	<Formfield name="Password" type="password" />
	<Button loading={$isSubmitting} type="submit">Sign up</Button>
</form>
<span class="text-fg1 text-center text-sm [&_a]:underline">
	Already have an account?
	<a href="/auth/signin">Sign in</a>
</span>

// src/components/signup.tsx
import { Button } from "@/components/ui/button";
import {
	Card,
	CardAction,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from "@/components/ui/card";
import {
	Form,
	FormControl,
	FormField,
	FormItem,
	FormLabel,
	FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { authClient } from "@/lib/auth/client";
import { zodResolver } from "@hookform/resolvers/zod";
import { LoaderCircle } from "lucide-react";
import React from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";

const formSchema = z.object({
	name: z.string().nonempty(),
	email: z.string().email().nonempty(),
	password: z.string().nonempty(),
});

export default function Signup(): React.JSX.Element {
	const [loading, setLoading] = React.useState(false);
	const form = useForm<z.infer<typeof formSchema>>({
		resolver: zodResolver(formSchema),
		defaultValues: {
			name: "",
			email: "",
			password: "",
		},
	});
	async function onSubmit(values: z.infer<typeof formSchema>) {
		setLoading(true);
		await authClient.signUp.email(
			{
				name: values.name,
				email: values.email,
				password: values.password,
			},
			{
				onResponse: () => setLoading(false),
				onSuccess: () => {
					toast.success("Successfully signed up.");
				},
				onError: ({ error }) => {
					toast.error(`Failed to sign up: ${error.message}`);
				},
			}
		);
	}
	return (
		<Card className="w-full max-w-sm self-center my-auto">
			<CardHeader>
				<CardTitle>Create your account</CardTitle>
				<CardDescription>
					Enter your email below to create an account.
				</CardDescription>
				<CardAction>
					<a href="/auth/signin">
						<Button variant="link">Sign in</Button>
					</a>
				</CardAction>
			</CardHeader>
			<CardContent>
				<Form {...form}>
					<form
						className="flex flex-col gap-8"
						onSubmit={form.handleSubmit(onSubmit)}
					>
						<FormField
							control={form.control}
							name="name"
							render={({ field }) => (
								<FormItem>
									<FormLabel>Username</FormLabel>
									<FormControl>
										<Input placeholder="Your Beautiful Name" {...field} />
									</FormControl>
									<FormMessage />
								</FormItem>
							)}
						/>
						<FormField
							control={form.control}
							name="email"
							render={({ field }) => (
								<FormItem>
									<FormLabel>Email</FormLabel>
									<FormControl>
										<Input placeholder="you@example.com" {...field} />
									</FormControl>
									<FormMessage />
								</FormItem>
							)}
						/>
						<FormField
							control={form.control}
							name="password"
							render={({ field }) => (
								<FormItem>
									<FormLabel>Password</FormLabel>
									<FormControl>
										<Input type="password" {...field} />
									</FormControl>
									<FormMessage />
								</FormItem>
							)}
						/>
						<Button type="submit" disabled={loading} className="w-full">
							{loading && <LoaderCircle className="animate-spin" />}
							Sign up
						</Button>
					</form>
				</Form>
			</CardContent>
		</Card>
	);
}
