// src/components/forms/signin.svelte
<script lang="ts">
	import Formfield from "./formfield.svelte";
	import Button from "@/components/button.svelte";
	import { newAuthClient as authClient } from "@/lib/auth/client";
	import { reporter } from "@felte/reporter-svelte";
	import { validator } from "@felte/validator-zod";
	import { navigate } from "astro:transitions/client";
	import { createForm } from "felte";
	import { toast } from "sonner";
	import { object, string, type infer as zInfer } from "zod";

	const schema = object({
		email: string().nonempty("required").email("invalid email"),
		password: string().nonempty("required"),
	});
	type Schema = zInfer<typeof schema>;

	const { form, isSubmitting } = createForm<Schema>({
		extend: [reporter(), validator({ schema })],
		onSubmit: async (values) => {
			await authClient.signIn.email(
				{
					email: values.email,
					password: values.password,
					rememberMe: true,
				},
				{
					onSuccess: () => {
						navigate("/");
					},
					onError: ({ error }) => {
						toast.error(`Failed to sign in: ${error.message}`);
					},
				}
			);
		},
	});
</script>

<form class="flex flex-col gap-2" use:form>
	<Formfield name="Email" />
	<Formfield name="Password" type="password" />
	<Button loading={$isSubmitting} type="submit">Sign in</Button>
</form>
<span class="text-fg1 text-center text-sm [&_a]:underline">
	<a href="/auth/reset">Forgot your password?</a>
	&bull;
	<a href="/auth/signup">Sign up</a>
</span>

// src/components/signin.tsx
import ResetDialog from "@/components/reset-dialog";
import { Button } from "@/components/ui/button";
import {
	Card,
	CardAction,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from "@/components/ui/card";
import {
	Form,
	FormControl,
	FormField,
	FormItem,
	FormLabel,
	FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { authClient } from "@/lib/auth/client";
import { zodResolver } from "@hookform/resolvers/zod";
import { navigate } from "astro:transitions/client";
import { LoaderCircle } from "lucide-react";
import React from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";

const formSchema = z.object({
	email: z.string().email().nonempty(),
	password: z.string().nonempty(),
});

export default function Signup(): React.JSX.Element {
	const [loading, setLoading] = React.useState(false);
	const form = useForm<z.infer<typeof formSchema>>({
		resolver: zodResolver(formSchema),
		defaultValues: {
			email: "",
			password: "",
		},
	});
	async function onSubmit(values: z.infer<typeof formSchema>) {
		setLoading(true);
		authClient.signIn.email(
			{
				email: values.email,
				password: values.password,
			},
			{
				onResponse: () => setLoading(false),
				onSuccess: () => navigate("/"),
				onError: ({ error }) => {
					toast.error(`Failed to sign in: ${error.message}`);
				},
			}
		);
	}
	return (
		<Card className="w-full max-w-sm self-center my-auto">
			<CardHeader>
				<CardTitle>Login to your account</CardTitle>
				<CardDescription>
					Enter your email below to login to your account.
				</CardDescription>
				<CardAction>
					<a href="/auth/signup">
						<Button variant="link">Sign up</Button>
					</a>
				</CardAction>
			</CardHeader>
			<CardContent>
				<Form {...form}>
					<form
						className="flex flex-col gap-8"
						onSubmit={form.handleSubmit(onSubmit)}
					>
						<FormField
							control={form.control}
							name="email"
							render={({ field }) => (
								<FormItem>
									<FormLabel>Email</FormLabel>
									<FormControl>
										<Input placeholder="you@example.com" {...field} />
									</FormControl>
									<FormMessage />
								</FormItem>
							)}
						/>
						<FormField
							control={form.control}
							name="password"
							render={({ field }) => (
								<FormItem>
									<div className="flex items-center">
										<FormLabel>Password</FormLabel>
										<span className="ml-auto inline-block">
											<ResetDialog />
										</span>
									</div>
									<FormControl>
										<Input type="password" {...field} />
									</FormControl>
									<FormMessage />
								</FormItem>
							)}
						/>
						<Button type="submit" disabled={loading} className="w-full">
							{loading && <LoaderCircle className="animate-spin" />}
							Sign in
						</Button>
					</form>
				</Form>
			</CardContent>
		</Card>
	);
}
