// src/components/title.tsx
import { Music2 } from "lucide-react";
import { useState, type JSX } from "react";

export default function Title({
	artist,
	id,
	title,
}: {
	id: string;
	title: string;
	artist: string;
}): JSX.Element {
	const [ok, setOk] = useState(true);
	return (
		<div className="flex gap-2 items-center">
			{!ok && (
				<span className="bg-muted rounded-sm flex items-center justify-center p-2">
					<Music2 className="text-muted-foreground" />
				</span>
			)}
			<img
				src={`/api/cover?id=${id}`}
				className={`size-10 rounded-sm ${ok ? "block" : "hidden"}`}
				onLoad={() => setOk(true)}
				onError={() => setOk(false)}
			/>
			<div className="flex flex-col">
				<span className="truncate">{title}</span>
				<span className="text-sm text-muted-foreground">{artist}</span>
			</div>
		</div>
	);
}

// src/components/storage/title.svelte
<script lang="ts">
	import type { track as trackTable } from "@/lib/schema";
	import { Avatar } from "bits-ui";
	import { Icon, MusicalNote } from "svelte-hero-icons";

	interface Props {
		track: typeof trackTable.$inferSelect;
	}
	const { track }: Props = $props();
</script>

<div class="flex items-center gap-1">
	<Avatar.Root>
		{#if track.cover}
			<Avatar.Image
				alt="{track.album || track.title} {track.album && 'album'} cover"
				class="size-10 rounded-sm"
				draggable={false}
				src="/api/track/cover/{track.id}"
			/>
		{/if}
		<Avatar.Fallback
			class="bg-bg1 flex size-10 items-center justify-center rounded-sm"
		>
			<Icon class="text-bg5 size-8" src={MusicalNote} />
		</Avatar.Fallback>
	</Avatar.Root>
	<div class="flex min-w-0 flex-col">
		<span class="truncate">{track.title}</span>
		<span class="text-fg2 truncate text-sm">{track.artist}</span>
	</div>
</div>
