// src/components/input.svelte
<script lang="ts">
	import { cn } from "../lib/utils";
	import type { ClassValue } from "clsx";
	import type { HTMLInputAttributes } from "svelte/elements";

	type Props = {
		class?: ClassValue;
	} & HTMLInputAttributes;
	const { class: className, ...props }: Props = $props();
</script>

<input
	class={cn(
		"aria-[invalid=true]:bg-destructive/30 aria-[invalid=true]:focus:ring-destructive/75! border-bg3 bg-bg1 placeholder:text-muted-foreground/80 disabled:border-foreground/50 focus-visible:ring-bg4/50 h-8 rounded-sm border px-3 text-sm focus:outline-none focus-visible:ring-[2.5px]",
		className
	)}
	{...props}
/>

// src/components/ui/input.tsx
import { cn } from "@/lib/utils";
import * as React from "react";

function Input({ className, type, ...props }: React.ComponentProps<"input">) {
	return (
		<input
			type={type}
			data-slot="input"
			className={cn(
				"file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input flex h-9 w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
				"focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]",
				"aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
				className
			)}
			{...props}
		/>
	);
}

export { Input };
